import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@6.1.0";
import { downloadDriveSubpath, downloadMcpServiceForDrive, escapeDriveQueryLiteral, normalizeDestination } from "./path.ts";

const SERVICE="download-drive";
const DRIVE_FILE_SCOPE="https://www.googleapis.com/auth/drive.file";
const REDIRECT_STRATEGY="reuse-notebook-callback";
const NOTEBOOK_CALLBACK="https://ezvfqrhzucjvkwnnbjux.supabase.co/functions/v1/gemini-notebook-mcp-prod/oauth/callback";
const EXECUTOR_REPO="QuJindai/automotive-smart-manufacturing-standards-archive";
const EXECUTOR_WORKFLOW=".github/workflows/download-executor.yml@refs/heads/main";
const OIDC_ISSUER="https://token.actions.githubusercontent.com";
const OIDC_AUDIENCE="download-mcp";
const OWNER_ID="00000000-0000-4000-8000-000000000091";
const ROOT_PROPERTY_KEY="download_plugin_root";
const ROOT_PROPERTY_VALUE="v1";
const ROOT_NAME="下载";
const FOLDER_MIME="application/vnd.google-apps.folder";
const DRIVE_API="https://www.googleapis.com/drive/v3";
const DRIVE_UPLOAD="https://www.googleapis.com/upload/drive/v3";
const GOOGLE_TOKEN_ENDPOINT="https://oauth2.googleapis.com/token";
const SUPABASE_URL=(Deno.env.get("SUPABASE_URL")??"").replace(/\/$/,"");
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const CONFIG_ENCRYPTION_KEY=Deno.env.get("CONFIG_ENCRYPTION_KEY")??"";
const JWKS=createRemoteJWKSet(new URL(`${OIDC_ISSUER}/.well-known/jwks`));
const encoder=new TextEncoder(),decoder=new TextDecoder();

type EncryptedBlob={iv:string;ciphertext:string};
type NotebookConfig={google_client_id:string;google_client_secret:string};
type StoredGoogleToken={access_token?:string;refresh_token?:string;expires_at?:number;scope?:string;token_type?:string};
type Bootstrap={attempt_version:number;original_encrypted_token:EncryptedBlob|null;started_at:string;expires_at:string};
type AuthPayload={authorized?:boolean;authorized_at?:string|null;scope?:string;redirect_strategy?:string;encrypted_token?:EncryptedBlob|null;bootstrap?:Bootstrap|null};
type AuthRow={payload:AuthPayload;revision:number};

if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error("Supabase runtime configuration is unavailable");

const cors={
  "access-control-allow-origin":"*",
  "access-control-allow-headers":"authorization, content-type",
  "access-control-allow-methods":"GET, POST, OPTIONS",
  "cache-control":"no-store",
  "x-content-type-options":"nosniff",
};
function json(body:unknown,status=200,extra:HeadersInit={}){return new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json; charset=utf-8",...extra}})}
function dbHeaders(contentType=false,prefer?:string):Record<string,string>{return{apikey:SERVICE_ROLE_KEY,authorization:`Bearer ${SERVICE_ROLE_KEY}`,accept:"application/json",...(contentType?{"content-type":"application/json"}:{}),...(prefer?{prefer}:{})}}
function base64ToBytes(value:string):Uint8Array<ArrayBuffer>{const raw=atob(value),out=new Uint8Array(new ArrayBuffer(raw.length));for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function cryptoKey(){if(CONFIG_ENCRYPTION_KEY.length<32)throw new Error("CONFIG_ENCRYPTION_KEY is unavailable");const d=await crypto.subtle.digest("SHA-256",encoder.encode(CONFIG_ENCRYPTION_KEY));return crypto.subtle.importKey("raw",d,{name:"AES-GCM"},false,["decrypt"])}
async function decryptJson<T>(blob:EncryptedBlob|null):Promise<T|null>{if(!blob)return null;const p=await crypto.subtle.decrypt({name:"AES-GCM",iv:base64ToBytes(blob.iv)},await cryptoKey(),base64ToBytes(blob.ciphertext));return JSON.parse(decoder.decode(p)) as T}
async function sha256Hex(value:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value)));return[...d].map(x=>x.toString(16).padStart(2,"0")).join("")}
function randomToken(bytes=32){const a=crypto.getRandomValues(new Uint8Array(bytes));let r="";for(const x of a)r+=String.fromCharCode(x);return btoa(r).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function sameBlob(a:EncryptedBlob|null,b:EncryptedBlob|null){return JSON.stringify(a??null)===JSON.stringify(b??null)}
function scopesOf(token:StoredGoogleToken|null){return new Set((token?.scope??"").split(/\s+/).filter(Boolean))}
function mimeFor(kind:string){if(kind==="pdf")return"application/pdf";if(kind==="gguf")return"application/octet-stream";if(kind==="zip")return"application/zip";if(kind==="safetensors")return"application/octet-stream";return"application/octet-stream"}
function safeName(value:string){const v=value.normalize("NFKC").replace(/[\\/\u0000-\u001f\u007f]/g,"-").trim().slice(0,180);return v||"download.bin"}

async function readAuthRow():Promise<AuthRow|null>{const q=new URLSearchParams({owner_id:`eq.${OWNER_ID}`,kind:"eq.download_google_auth",record_id:"eq.default",select:"payload,revision"});const r=await fetch(`${SUPABASE_URL}/rest/v1/iaos_mcp_state?${q}`,{headers:dbHeaders()});if(!r.ok)throw new Error(`auth state read failed: ${r.status}`);const rows=await r.json();return rows?.[0]?{payload:rows[0].payload??{},revision:Number(rows[0].revision??1)}:null}
async function saveAuthPayload(payload:AuthPayload){const e=await readAuthRow();if(e){const q=new URLSearchParams({owner_id:`eq.${OWNER_ID}`,kind:"eq.download_google_auth",record_id:"eq.default",revision:`eq.${e.revision}`});const r=await fetch(`${SUPABASE_URL}/rest/v1/iaos_mcp_state?${q}`,{method:"PATCH",headers:dbHeaders(true,"return=minimal"),body:JSON.stringify({payload,revision:e.revision+1,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(`auth state update failed: ${r.status}`);return}const r=await fetch(`${SUPABASE_URL}/rest/v1/iaos_mcp_state`,{method:"POST",headers:dbHeaders(true,"return=minimal"),body:JSON.stringify({owner_id:OWNER_ID,kind:"download_google_auth",record_id:"default",payload,revision:1})});if(!r.ok)throw new Error(`auth state create failed: ${r.status}`)}
async function readNotebookConfigRow():Promise<{encrypted_config:EncryptedBlob;encrypted_token:EncryptedBlob|null;oauth_attempt_version:number}>{const q=new URLSearchParams({id:"eq.default",select:"encrypted_config,encrypted_token,oauth_attempt_version"});const r=await fetch(`${SUPABASE_URL}/rest/v1/gemini_notebook_connector_config?${q}`,{headers:dbHeaders()});if(!r.ok)throw new Error(`Notebook config read failed: ${r.status}`);const rows=await r.json(),row=rows?.[0];if(!row?.encrypted_config)throw new Error("Notebook Google OAuth client is not configured");return{encrypted_config:row.encrypted_config,encrypted_token:row.encrypted_token??null,oauth_attempt_version:Number(row.oauth_attempt_version??0)}}
async function adoptionPlan(){const auth=await readAuthRow(),notebook=await readNotebookConfigRow(),bootstrap=auth?.payload.bootstrap??null,token=await decryptJson<StoredGoogleToken>(notebook.encrypted_token),scopes=scopesOf(token);const pending=Boolean(bootstrap),matches=Boolean(bootstrap)&&bootstrap!.attempt_version===notebook.oauth_attempt_version,has=scopes.has(DRIVE_FILE_SCOPE),notExpired=Boolean(bootstrap)&&Number.isFinite(Date.parse(bootstrap!.expires_at))&&Date.parse(bootstrap!.expires_at)>Date.now(),tokenChanged=Boolean(bootstrap)&&!sameBlob(bootstrap!.original_encrypted_token,notebook.encrypted_token);return{service:SERVICE,bootstrap_pending:pending,attempt_matches:matches,current_has_drive_file:has,token_changed:tokenChanged,eligible_to_adopt:pending&&matches&&has&&notExpired&&tokenChanged,bootstrap_expired:pending&&!notExpired}}
async function maybeAdopt(){const row=await readAuthRow();if(row?.payload.authorized===true&&row.payload.encrypted_token)return row.payload;const notebook=await readNotebookConfigRow(),bootstrap=row?.payload.bootstrap??null;if(!bootstrap)return row?.payload??{};const token=await decryptJson<StoredGoogleToken>(notebook.encrypted_token),has=scopesOf(token).has(DRIVE_FILE_SCOPE),matches=bootstrap.attempt_version===notebook.oauth_attempt_version,notExpired=Date.parse(bootstrap.expires_at)>Date.now(),changed=!sameBlob(bootstrap.original_encrypted_token,notebook.encrypted_token);if(!(has&&matches&&notExpired&&changed))return row?.payload??{};const payload:AuthPayload={authorized:true,authorized_at:new Date().toISOString(),scope:DRIVE_FILE_SCOPE,redirect_strategy:REDIRECT_STRATEGY,encrypted_token:notebook.encrypted_token,bootstrap:null};await saveAuthPayload(payload);return payload}
async function readAuthState(){const p=await maybeAdopt();return{authorized:p.authorized===true,authorized_at:typeof p.authorized_at==="string"?p.authorized_at:null}}
async function beginNotebookOAuth(state:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/begin_gemini_notebook_oauth_attempt`,{method:"POST",headers:dbHeaders(true),body:JSON.stringify({p_state_hash:await sha256Hex(state)})});if(!r.ok)throw new Error(`OAuth state start failed: ${r.status}`);const data=await r.json(),v=Array.isArray(data)?data[0]:data,attempt=Number(v?.attempt_version??v??0);if(!Number.isSafeInteger(attempt)||attempt<1)throw new Error("OAuth attempt version missing");return attempt}
async function oauthStart(){const current=await readAuthState();if(current.authorized)return json({code:"ALREADY_AUTHORIZED",authorized:true},409);const auth=await readAuthRow();if(auth?.payload.bootstrap&&Date.parse(auth.payload.bootstrap.expires_at)>Date.now())return json({code:"AUTHORIZATION_IN_PROGRESS",expires_at:auth.payload.bootstrap.expires_at},409);const row=await readNotebookConfigRow(),config=await decryptJson<NotebookConfig>(row.encrypted_config);if(!config?.google_client_id)throw new Error("Notebook Google OAuth client ID is unavailable");const state=randomToken(32),attempt=await beginNotebookOAuth(state),now=Date.now();await saveAuthPayload({authorized:false,authorized_at:null,scope:DRIVE_FILE_SCOPE,redirect_strategy:REDIRECT_STRATEGY,encrypted_token:null,bootstrap:{attempt_version:attempt,original_encrypted_token:row.encrypted_token,started_at:new Date(now).toISOString(),expires_at:new Date(now+600000).toISOString()}});const params=new URLSearchParams({client_id:config.google_client_id,redirect_uri:NOTEBOOK_CALLBACK,response_type:"code",access_type:"offline",prompt:"consent",include_granted_scopes:"true",state,scope:["openid","email","profile","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/discoveryengine.readwrite","https://www.googleapis.com/auth/drive.readonly",DRIVE_FILE_SCOPE].join(" ")});return Response.redirect(`https://accounts.google.com/o/oauth2/v2/auth?${params}`,302)}

async function googleAccessToken(){const p=await maybeAdopt();if(p.authorized!==true||!p.encrypted_token)throw new Error("Google Drive write authorization is required");const stored=await decryptJson<StoredGoogleToken>(p.encrypted_token);if(!stored)throw new Error("Google Drive token is unavailable");const expires=Number(stored.expires_at??0);const expiresMs=expires>10_000_000_000?expires:expires*1000;if(stored.access_token&&expiresMs>Date.now()+60_000)return stored.access_token;if(!stored.refresh_token)throw new Error("Google Drive refresh token is unavailable");const notebook=await readNotebookConfigRow(),config=await decryptJson<NotebookConfig>(notebook.encrypted_config);if(!config?.google_client_id||!config.google_client_secret)throw new Error("Google OAuth client is unavailable");const r=await fetch(GOOGLE_TOKEN_ENDPOINT,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:config.google_client_id,client_secret:config.google_client_secret,refresh_token:stored.refresh_token,grant_type:"refresh_token"})});if(!r.ok)throw new Error(`Google token refresh failed: ${r.status}`);const t=await r.json();if(!t?.access_token)throw new Error("Google token refresh returned no access token");return String(t.access_token)}
async function driveFetch(url:string,init:RequestInit={}){const token=await googleAccessToken();const h=new Headers(init.headers);h.set("authorization",`Bearer ${token}`);if(!h.has("accept"))h.set("accept","application/json");const r=await fetch(url,{...init,headers:h,signal:AbortSignal.timeout(30_000)});if(!r.ok)throw new Error(`Google Drive request failed: ${r.status}`);return r}
async function ensureRootFolder(){const q=`trashed = false and mimeType = '${FOLDER_MIME}' and appProperties has { key='${ROOT_PROPERTY_KEY}' and value='${ROOT_PROPERTY_VALUE}' }`;const u=new URL(`${DRIVE_API}/files`);u.searchParams.set("q",q);u.searchParams.set("spaces","drive");u.searchParams.set("pageSize","2");u.searchParams.set("fields","files(id,name,mimeType,parents,webViewLink,trashed)");const listed=await driveFetch(u.toString());const data=await listed.json();const files=Array.isArray(data?.files)?data.files:[];if(files.length>1)throw new Error("Multiple Download plugin root folders exist");if(files[0]?.id)return files[0];const created=await driveFetch(`${DRIVE_API}/files?fields=id,name,mimeType,parents,webViewLink`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:ROOT_NAME,mimeType:FOLDER_MIME,appProperties:{[ROOT_PROPERTY_KEY]:ROOT_PROPERTY_VALUE}})});return await created.json()}
async function listDriveFiles(query:string,fields:string){const u=new URL(`${DRIVE_API}/files`);u.searchParams.set("q",query);u.searchParams.set("spaces","drive");u.searchParams.set("pageSize","2");u.searchParams.set("fields",fields);const listed=await driveFetch(u.toString());const data=await listed.json();return Array.isArray(data?.files)?data.files:[]}
async function createDriveFolder(parentId:string,name:string){const created=await driveFetch(`${DRIVE_API}/files?fields=id,name,mimeType,parents,webViewLink`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,mimeType:FOLDER_MIME,parents:[parentId],appProperties:{download_plugin:"v1"}})});return await created.json()}
async function ensureChildFolder(parentId:string,name:string){const escapedName=escapeDriveQueryLiteral(name),escapedParent=escapeDriveQueryLiteral(parentId);const query=`trashed = false and mimeType = '${FOLDER_MIME}' and name = '${escapedName}' and '${escapedParent}' in parents`;const files=await listDriveFiles(query,"files(id,name,mimeType,parents,webViewLink,trashed)");if(files.length>1)throw new Error("Multiple destination folders match the same parent/name");if(files[0]?.id)return files[0];return await createDriveFolder(parentId,name)}
async function ensureDestinationFolder(destination:unknown){const segments=normalizeDestination(destination);const root=await ensureRootFolder();let folder=root;for(const segment of segments)folder=await ensureChildFolder(folder.id,segment);return{root,folder,segments}}
async function createUploadSession(asset:any,parentId:string){const name=safeName(String(asset?.filename??"download.bin")),kind=String(asset?.kind??"binary"),mime=mimeFor(kind);const u=new URL(`${DRIVE_UPLOAD}/files`);u.searchParams.set("uploadType","resumable");u.searchParams.set("fields","id,name,size,webViewLink,parents");const h:Record<string,string>={"content-type":"application/json; charset=UTF-8","x-upload-content-type":mime};const size=Number(asset?.expected_size_bytes??0);if(Number.isSafeInteger(size)&&size>0)h["x-upload-content-length"]=String(size);const r=await driveFetch(u.toString(),{method:"POST",headers:h,body:JSON.stringify({name,mimeType:mime,parents:[parentId],appProperties:{download_plugin:"v1",download_asset_id:String(asset?.asset_id??"")}})});const location=r.headers.get("location");await r.body?.cancel();if(!location)throw new Error("Drive resumable session URL missing");return location}
async function driveMetadata(fileId:string){const r=await driveFetch(`${DRIVE_API}/files/${encodeURIComponent(fileId)}?fields=id,name,size,webViewLink,parents,trashed&supportsAllDrives=true`);return await r.json()}

async function verifyExecutor(req:Request){const token=(req.headers.get("authorization")??"").replace(/^Bearer\s+/i,"").trim();if(!token)throw new Error("missing executor OIDC token");const{payload}=await jwtVerify(token,JWKS,{issuer:OIDC_ISSUER,audience:OIDC_AUDIENCE});if(String(payload.repository??"")!==EXECUTOR_REPO)throw new Error("executor repository not allowed");if(String(payload.ref??"")!=="refs/heads/main")throw new Error("executor ref not allowed");if(!String(payload.workflow_ref??"").includes(EXECUTOR_WORKFLOW))throw new Error("executor workflow not allowed");return token}
async function fetchJob(downloadId:string,oidc:string,controlService:string){const r=await fetch(`${SUPABASE_URL}/functions/v1/${controlService}/executor/job/${encodeURIComponent(downloadId)}`,{headers:{authorization:`Bearer ${oidc}`,accept:"application/json"}});if(!r.ok)throw new Error(`Download control job read failed: ${r.status}`);return await r.json()}
async function sessions(downloadId:string,oidc:string,controlService:string){const state=await readAuthState();if(!state.authorized)return{authRequired:true,body:{code:"AUTH_REQUIRED",scope:DRIVE_FILE_SCOPE,authorization_url:`${SUPABASE_URL}/functions/v1/${SERVICE}/oauth/start`}};const job=await fetchJob(downloadId,oidc,controlService),destination=await ensureDestinationFolder(job?.destination),assets=Array.isArray(job?.assets)?job.assets:[],out:Record<string,string>={};for(const asset of assets){if(!asset||typeof asset!=="object")continue;const id=String(asset.asset_id??"");if(!id)continue;out[id]=await createUploadSession(asset,destination.folder.id)}return{authRequired:false,body:{download_id:downloadId,root_folder:{id:destination.root.id,name:destination.root.name,web_url:destination.root.webViewLink??`https://drive.google.com/drive/folders/${destination.root.id}`},destination_folder:{id:destination.folder.id,name:destination.folder.name,web_url:destination.folder.webViewLink??`https://drive.google.com/drive/folders/${destination.folder.id}`},destination_segments:destination.segments,upload_sessions:out}}}
async function verifyRefs(downloadId:string,refs:any[],oidc:string,controlService:string){const job=await fetchJob(downloadId,oidc,controlService),destination=await ensureDestinationFolder(job?.destination),verified=[];for(const ref of refs){const id=String(ref?.file_id??"");if(!id)throw new Error("Drive ref file_id missing");const m=await driveMetadata(id);if(m?.trashed||!Array.isArray(m?.parents)||!m.parents.includes(destination.folder.id))throw new Error("Drive file is not in the expected destination folder");const expectedSize=Number(ref?.size??0);if(expectedSize>0&&Number(m?.size??0)!==expectedSize)throw new Error("Drive file size mismatch");verified.push({file_id:id,name:String(m?.name??ref?.name??""),size:Number(m?.size??0),web_url:m?.webViewLink??`https://drive.google.com/file/d/${id}/view`,sha256:String(ref?.sha256??""),parents:m.parents})}return{download_id:downloadId,verified:true,destination_folder:{id:destination.folder.id,name:destination.folder.name,web_url:destination.folder.webViewLink??`https://drive.google.com/drive/folders/${destination.folder.id}`},destination_segments:destination.segments,drive_refs:verified}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});const url=new URL(req.url),sub=downloadDriveSubpath(url.pathname),controlService=downloadMcpServiceForDrive(url.pathname);
if(req.method==="GET"&&sub==="/oauth/status"){try{const s=await readAuthState();return json({service:SERVICE,scope:DRIVE_FILE_SCOPE,authorized:s.authorized,authorized_at:s.authorized_at,redirect_strategy:REDIRECT_STRATEGY})}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}}
if(req.method==="GET"&&sub==="/oauth/start"){try{return await oauthStart()}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}}
if(req.method==="GET"&&sub==="/oauth/adoption-plan"){try{return json(await adoptionPlan())}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}}
const sm=/^\/executor\/sessions\/([^/]+)$/.exec(sub);if(req.method==="POST"&&sm){let oidc="";try{oidc=await verifyExecutor(req);const r=await sessions(decodeURIComponent(sm[1]),oidc,controlService);return json(r.body,r.authRequired?409:200)}catch(e){return json({error:e instanceof Error?e.message:String(e)},401)}}
const vm=/^\/executor\/verify\/([^/]+)$/.exec(sub);if(req.method==="POST"&&vm){try{const oidc=await verifyExecutor(req);const body=await req.json();const refs=Array.isArray(body?.drive_refs)?body.drive_refs:[];if(!refs.length)throw new Error("drive_refs required");return json(await verifyRefs(decodeURIComponent(vm[1]),refs,oidc,controlService))}catch(e){return json({error:e instanceof Error?e.message:String(e)},400)}}
return json({error:"not_found"},404)});

